# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_iw1ip5oUcBAV5d_drR7xydKV0u5IdFR
"""

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Устанавливаем случайный seed для воспроизводимости
np.random.seed(42)

# 1. Генерация численных данных
data = pd.Series(np.random.randint(-10000, 10001, size=1000))

# 2. Проверка на наличие пропусков (null) или некорректных значений перед анализом
print("=== Проверка данных на наличие пропусков и некорректных значений ===")
null_count = data.isnull().sum()
print(f"Количество пропусков (null): {null_count}")

# Проверка на бесконечность
inf_count = np.isinf(data).sum()
print(f"Количество бесконечных значений: {inf_count}")

# Проверка на значения вне заданного диапазона
invalid_range = ((data < -10000) | (data > 10000)).sum()
print(f"Количество значений вне диапазона [-10000, 10000]: {invalid_range}")

if null_count == 0 and inf_count == 0 and invalid_range == 0:
    print("Все данные корректны, пропусков нет\n")
else:
    print("Обнаружены некорректные значения, требуется очистка\n")

# 3. Обработка от цифрового мусора (очистка данных)
print("=== Обработка от цифрового мусора ===")

# Создаем копию для очистки
data_cleaned = data.copy()

# Убираем пропуски (если есть)
data_cleaned = data_cleaned.dropna()

# Убираем бесконечные значения
data_cleaned = data_cleaned[~np.isinf(data_cleaned)]

# Убираем значения вне заданного диапазона
data_cleaned = data_cleaned[(data_cleaned >= -10000) & (data_cleaned <= 10000)]

print(f"Original count: {len(data)}")
print(f"Cleaned count: {len(data_cleaned)}")
print(f"Удалено элементов: {len(data) - len(data_cleaned)}\n")

# Используем очищенные данные (если они отличаются от оригинала)
data_to_use = data_cleaned if len(data_cleaned) < len(data) else data

# 4. Преобразование Series в DataFrame со столбцом «Original_Data»
print("=== Преобразование Series в DataFrame ===")
df = pd.DataFrame({'Original_Data': data_to_use})
print(f"DataFrame создан с столбцом 'Original_Data'")
print(f"Количество строк: {len(df)}")
print(f"Структура DataFrame:")
print(df.head())
print(f"\nНазвания столбцов: {df.columns.tolist()}\n")

# 5. Расчёт стандартных числовых характеристик для Original_Data
min_value = df['Original_Data'].min()
max_value = df['Original_Data'].max()
sum_value = df['Original_Data'].sum()
std_dev = df['Original_Data'].std()
# Количество повторяющихся значений = общее количество - количество уникальных
repeated_count = len(df['Original_Data']) - df['Original_Data'].nunique()

# 6. Вывод результатов в консоль с пояснениями
print("=== Стандартные числовые характеристики ===")
print(f"Минимальное значение: {min_value}")
print(f"Максимальное значение: {max_value}")
print(f"Сумма чисел: {sum_value}")
print(f"Среднеквадратическое отклонение: {std_dev:.2f}")
print(f"Количество повторяющихся значений: {repeated_count}")
print(f"Общее количество чисел: {len(df['Original_Data'])}")
print(f"Количество уникальных чисел: {df['Original_Data'].nunique()}\n")

# 7. Сохранение DataFrame (с Original_Data) в CSV файл
csv_filename = 'simple_analysis_data.csv'
df.to_csv(csv_filename, index=False)
print(f"=== DataFrame сохранён в CSV файл: {csv_filename} ===\n")

# 8. Обработка CSV файла (читаем обратно и анализируем)
print("=== Обработка CSV файла ===")
df_from_csv = pd.read_csv(csv_filename)
print(f"Структура CSV файла:")
print(df_from_csv.head())
print(f"\nКоличество строк в CSV: {len(df_from_csv)}")
print(f"Названия столбцов: {df_from_csv.columns.tolist()}")

# Проверка данных из CSV
csv_null_count = df_from_csv['Original_Data'].isnull().sum()
print(f"Пропусков в CSV данных: {csv_null_count}")

# 9. Визуализация данных (используем данные из CSV для демонстрации)
plt.figure(figsize=(12, 5))

# Линейный график
plt.subplot(1, 2, 1)
plt.plot(df_from_csv.index, df_from_csv['Original_Data'].values, linewidth=1, color='steelblue')
plt.title("Линейный график исходных данных")
plt.xlabel("Индекс")
plt.ylabel("Значение")
plt.grid(True, alpha=0.3)

# Гистограмма с округлением до сотен (математическое правило)
plt.subplot(1, 2, 2)
rounded_data = df_from_csv['Original_Data'].apply(lambda x: int(math.floor(x / 100 + 0.5)) * 100)
plt.hist(rounded_data, bins=range(rounded_data.min(), rounded_data.max() + 100, 100),
         rwidth=0.8, edgecolor='black', color='coral')
plt.title("Гистограмма (округление до сотен)")
plt.xlabel("Значение")
plt.ylabel("Частота")
plt.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('visualization_1.png', dpi=150)
print("График 1 сохранён: visualization_1.png")
plt.show()
plt.close()

# 10. Добавление столбцов с отсортированными значениями
df['sorted_asc'] = df['Original_Data'].sort_values().reset_index(drop=True)
df['sorted_desc'] = df['Original_Data'].sort_values(ascending=False).reset_index(drop=True)

print(f"\n=== DataFrame с отсортированными столбцами ===")
print(f"Столбцы: {df.columns.tolist()}")
print(df.head())

# 11. Визуализация отсортированных значений на одном графике
plt.figure(figsize=(12, 5))
plt.plot(df['sorted_asc'].values, label='По возрастанию', linewidth=1, color='green')
plt.plot(df['sorted_desc'].values, label='По убыванию', linewidth=1, color='red')
plt.title("Отсортированные значения: возрастание и убывание")
plt.xlabel("Индекс")
plt.ylabel("Значение")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('visualization_2.png', dpi=150)
print("График 2 сохранён: visualization_2.png")
plt.show()
plt.close()

# 12. Сохранение итокового DataFrame в CSV
df_csv_filename = 'simple_analysis_dataframe.csv'
df.to_csv(df_csv_filename, index=False)
print(f"\n=== Итоговый DataFrame сохранён в CSV файл: {df_csv_filename} ===")

# 13. Дополнительная обработка DataFrame из CSV
df_final_from_csv = pd.read_csv(df_csv_filename)
print(f"\n=== Анализ сохранённого итогового DataFrame ===")
print(f"Структура DataFrame:")
print(df_final_from_csv.head())
print(f"\nКоличество строк: {len(df_final_from_csv)}")
print(f"Столбцы: {df_final_from_csv.columns.tolist()}")

# Быстрая статистика для DataFrame
print(f"\n=== Быстрая статистика DataFrame ===")
print(df_final_from_csv.describe())

print("\n Все задачи выполнены успешно!")